### ISSUE TITLE
On clicking the pause button then resume should show on button

### ISSUE THREAD

**Issue by swapnilsparsh** [dscabesit/Youtube-Downloader#10]

**Comment by omnone** [comment]
Hey can you assign this to me? Thanks

**Comment by dinukad** [comment]
@swapnilsparsh I would like to work on this. Please assign me this issue

**Comment by swapnilsparsh** [comment]
@dinukad Anyone can do the work.

**Comment by foxieze** [comment]
I think this should already happen:

main.py - Ln 78
```
def toggle_download():
    global is_paused
    is_paused = not is_paused
    pause_button['text'] = 'Resume' if is_paused else 'Pause'
```

**Comment by dinukad** [comment]
> I think this should already happen:
> 
> main.py - Ln 78
> 
> ```
> def toggle_download():
>     global is_paused
>     is_paused = not is_paused
>     pause_button['text'] = 'Resume' if is_paused else 'Pause'
> ```

@jonahcrowlinson yes, when I try to fix and create a PR, there is nothing to fix :)

**Comment by swapnilsparsh** [comment]
![Annotation 2020-10-07 204810](https://user-images.githubusercontent.com/69387608/95351161-89a53680-08de-11eb-8762-85ff3482c1d5.png)

After pausing the progress, it doesn't change to resume.
@dinukad Refer the above Screenshot

**Comment by foxieze** [comment]
One quick fix to this would be to just change the text to "Toggle Pause" but otherwise we would change the text (which shouldn't be hard)



________________________________

**Comment by swapnilsparsh** [comment]
Do the required changes and then send a PR. @jonahcrowlinson

**Comment by zendamacf** [comment]
Hi, turns out changing the text of the button wasn't doing anything, because the button was an image. I added a `Resume` image instead, and created the linked pull request.
