### ISSUE TITLE
Downloaded file should has the same name as of the Video

### ISSUE THREAD

**Issue by swapnilsparsh** [dscabesit/Youtube-Downloader#11]

**Comment by Harsh-Udai** [comment]
hey @swapnilsparsh  can you assign this to me, i would like to work on this.

**Comment by swapnilsparsh** [comment]
@HarshUdai ok do the work

**Comment by nishant-mor** [comment]
@swapnilsparsh Hey I was working on it and forgot to ask for assignment.

**Comment by swapnilsparsh** [comment]
Thank you @nishant-mor for solving the issue
